# Generated by Django 4.1.4 on 2022-12-21 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pessoa",
            new_name="People",
        ),
    ]
