# Generated by Django 4.1.4 on 2022-12-21 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0002_rename_pessoa_people"),
    ]

    operations = [
        migrations.RenameField(
            model_name="people",
            old_name="nome",
            new_name="name",
        ),
    ]
